### ISSUE TITLE
Doesn't build today - symbol conflict

### ISSUE THREAD

**Issue by quicklisp** [cbaggers/cepl.skitter#1]
http://report.quicklisp.org/2017-06-19/failure-report/cepl.skitter.html#cepl.skitter.glop has the log.

    Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {10023F7683}>: Can't inherit "WINDOW-SIZE" from "SKITTER", it is inherited from "CEPL.HOST"

**Comment by cbaggers** [comment]
Thanks, should be fixed now
